// =============================================================================
// Kural Sevi — Curated NSQF Trade Catalog Seed
// High-SC representation trades aligned with PM-AJAY Track 2 & NSDC QP-NOS.
// Serves as local seed and offline fallback.
// =============================================================================

import type { NSQFTrade } from '@kural-sevi/shared';

export const NSQF_CATALOG_SEED: NSQFTrade[] = [
  // TEXTILE & APPAREL
  {
    qp_code: 'TEX/Q4101',
    qp_name: 'Weaving Machine Operator',
    sector: 'Textile',
    nsqf_level: 4,
    pathway_type: 'wage_employment',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: true,
    min_education_years: 8,
    typical_income_min: 8000,
    typical_income_max: 15000,
    training_duration_hours: 200,
    description: 'Operates power looms and handlooms to weave fabrics',
    required_skills: ['basic_manual_dexterity'],
    skills_acquired: ['loom_operation', 'fabric_inspection', 'quality_control'],
  },
  {
    qp_code: 'APP/Q0103',
    qp_name: 'Sewing Machine Operator',
    sector: 'Apparel',
    nsqf_level: 2,
    pathway_type: 'self_employment',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 5,
    typical_income_min: 6000,
    typical_income_max: 18000,
    training_duration_hours: 120,
    description: 'Operates industrial sewing machines for garment production',
    required_skills: ['basic_stitching'],
    skills_acquired: ['industrial_sewing', 'garment_assembly', 'basic_pattern_cutting'],
  },
  {
    qp_code: 'APP/Q0301',
    qp_name: "Tailor - Women's and Men's Garment",
    sector: 'Apparel',
    nsqf_level: 4,
    pathway_type: 'self_employment',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 5,
    typical_income_min: 8000,
    typical_income_max: 25000,
    training_duration_hours: 300,
    description: 'Designs and stitches custom garments for clients',
    required_skills: ['hand_stitching', 'measurement_taking'],
    skills_acquired: ['pattern_making', 'garment_fitting', 'embroidery_basics'],
  },
  {
    qp_code: 'HAN/Q0101',
    qp_name: 'Handloom Weaver',
    sector: 'Handicrafts & Carpet',
    nsqf_level: 3,
    pathway_type: 'home_enterprise',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 0,
    typical_income_min: 6000,
    typical_income_max: 20000,
    training_duration_hours: 180,
    description: 'Produces traditional handloom textiles using traditional techniques',
    required_skills: ['traditional_weaving_knowledge'],
    skills_acquired: ['handloom_operation', 'natural_dyeing', 'design_replication'],
  },
  {
    qp_code: 'HAN/Q0301',
    qp_name: 'Artisan - Block Printing',
    sector: 'Handicrafts & Carpet',
    nsqf_level: 3,
    pathway_type: 'home_enterprise',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 0,
    typical_income_min: 5000,
    typical_income_max: 15000,
    training_duration_hours: 150,
    description: 'Applies traditional block printing on fabric and paper',
    required_skills: ['artistic_sense', 'color_mixing'],
    skills_acquired: ['block_making', 'printing_techniques', 'fabric_preparation'],
  },

  // FOOD PROCESSING & RETAIL
  {
    qp_code: 'FIC/Q0201',
    qp_name: 'Pickle Making Technician',
    sector: 'Food Industry',
    nsqf_level: 2,
    pathway_type: 'home_enterprise',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 0,
    typical_income_min: 5000,
    typical_income_max: 20000,
    training_duration_hours: 100,
    description: 'Produces pickles and chutneys for local and commercial sale',
    required_skills: ['basic_cooking'],
    skills_acquired: ['preservation_techniques', 'hygiene_practices', 'packaging', 'labeling'],
  },
  {
    qp_code: 'FIC/Q0601',
    qp_name: 'Food Processing Entrepreneur',
    sector: 'Food Industry',
    nsqf_level: 4,
    pathway_type: 'self_employment',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 5,
    typical_income_min: 10000,
    typical_income_max: 30000,
    training_duration_hours: 240,
    description: 'Sets up and manages a small food processing unit',
    required_skills: ['cooking', 'business_basics'],
    skills_acquired: ['production_planning', 'quality_assurance', 'costing', 'market_linkage'],
  },
  {
    qp_code: 'FIC/Q5001',
    qp_name: 'Papad and Ready-to-Eat Products Maker',
    sector: 'Food Industry',
    nsqf_level: 2,
    pathway_type: 'home_enterprise',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 0,
    typical_income_min: 4000,
    typical_income_max: 15000,
    training_duration_hours: 80,
    description: 'Prepares traditional ready-to-eat food products for local markets',
    required_skills: ['traditional_cooking'],
    skills_acquired: ['standardized_recipes', 'hygiene', 'pricing', 'local_distribution'],
  },

  // AGRICULTURE & ALLIED
  {
    qp_code: 'AGR/Q4101',
    qp_name: 'Organic Farming Technician',
    sector: 'Agriculture',
    nsqf_level: 4,
    pathway_type: 'self_employment',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 5,
    typical_income_min: 8000,
    typical_income_max: 20000,
    training_duration_hours: 200,
    description: 'Practices and teaches organic farming methods',
    required_skills: ['farming_background'],
    skills_acquired: ['soil_testing', 'composting', 'natural_pest_management', 'crop_rotation'],
  },
  {
    qp_code: 'AGR/Q1201',
    qp_name: 'Nursery Worker',
    sector: 'Agriculture',
    nsqf_level: 3,
    pathway_type: 'wage_employment',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 0,
    typical_income_min: 7000,
    typical_income_max: 13000,
    training_duration_hours: 120,
    description: 'Grows and tends plants in a commercial nursery',
    required_skills: ['basic_farming'],
    skills_acquired: ['seed_germination', 'plant_care', 'grafting', 'pest_identification'],
  },
  {
    qp_code: 'AHC/Q0401',
    qp_name: 'Livestock Farmer / Pashudhan Mitra',
    sector: 'Agriculture',
    nsqf_level: 4,
    pathway_type: 'self_employment',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: true,
    min_education_years: 0,
    typical_income_min: 8000,
    typical_income_max: 25000,
    training_duration_hours: 240,
    description: 'Manages small-scale livestock farming and animal husbandry',
    required_skills: ['animal_care_experience'],
    skills_acquired: ['animal_nutrition', 'disease_prevention', 'milk_production', 'record_keeping'],
  },

  // RETAIL & TRADING
  {
    qp_code: 'RAS/Q0104',
    qp_name: 'Retail Sales Associate / Shopkeeper',
    sector: 'Retail',
    nsqf_level: 3,
    pathway_type: 'self_employment',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 5,
    typical_income_min: 9000,
    typical_income_max: 22000,
    training_duration_hours: 120,
    description: 'Assists customers, manages retail sales, shop inventory and store billing',
    required_skills: ['basic_numeracy', 'communication', 'vegetable_selling'],
    skills_acquired: ['customer_service', 'inventory_management', 'cash_handling', 'product_knowledge'],
  },

  // BEAUTY & WELLNESS
  {
    qp_code: 'BWS/Q0201',
    qp_name: 'Beauty Therapist',
    sector: 'Beauty & Wellness',
    nsqf_level: 4,
    pathway_type: 'self_employment',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 8,
    typical_income_min: 12000,
    typical_income_max: 35000,
    training_duration_hours: 300,
    description: 'Provides beauty and grooming services to clients',
    required_skills: ['interpersonal_skills'],
    skills_acquired: ['skincare', 'makeup', 'hair_styling', 'salon_management'],
  },
  {
    qp_code: 'BWS/Q0501',
    qp_name: 'Mehendi Artist',
    sector: 'Beauty & Wellness',
    nsqf_level: 3,
    pathway_type: 'self_employment',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 0,
    typical_income_min: 5000,
    typical_income_max: 30000,
    training_duration_hours: 100,
    description: 'Creates traditional and contemporary mehendi designs',
    required_skills: ['artistic_skill', 'steady_hands'],
    skills_acquired: ['design_patterns', 'cone_preparation', 'client_consultation'],
  },

  // ELECTRICAL & SOLAR
  {
    qp_code: 'ELE/Q3101',
    qp_name: 'Electrician (Domestic)',
    sector: 'Capital Goods',
    nsqf_level: 4,
    pathway_type: 'self_employment',
    gender_eligible: 'all',
    requires_mobility: true,
    requires_physical_strength: false,
    min_education_years: 8,
    typical_income_min: 12000,
    typical_income_max: 28000,
    training_duration_hours: 200,
    description: 'Installs and maintains domestic electrical systems',
    required_skills: ['basic_math', 'tools_handling'],
    skills_acquired: ['wiring', 'switchboard_installation', 'fan_motor_repair', 'safety_practices'],
  },
  {
    qp_code: 'ELE/Q6801',
    qp_name: 'Solar Panel Installation Technician',
    sector: 'Capital Goods',
    nsqf_level: 4,
    pathway_type: 'wage_employment',
    gender_eligible: 'all',
    requires_mobility: true,
    requires_physical_strength: true,
    min_education_years: 10,
    typical_income_min: 13000,
    typical_income_max: 25000,
    training_duration_hours: 180,
    description: 'Installs and maintains solar photovoltaic panels and systems',
    required_skills: ['electrical_basics'],
    skills_acquired: ['panel_mounting', 'wiring_DC_AC', 'inverter_setup', 'performance_monitoring'],
  },

  // HEALTHCARE SUPPORT
  {
    qp_code: 'HSS/Q0601',
    qp_name: 'Home Health Aide',
    sector: 'Healthcare',
    nsqf_level: 3,
    pathway_type: 'wage_employment',
    gender_eligible: 'all',
    requires_mobility: true,
    requires_physical_strength: false,
    min_education_years: 8,
    typical_income_min: 8000,
    typical_income_max: 18000,
    training_duration_hours: 150,
    description: 'Provides in-home care and assistance to patients and elderly',
    required_skills: ['care_giving_experience', 'empathy'],
    skills_acquired: ['personal_care', 'vital_signs_monitoring', 'medication_reminders', 'mobility_assistance'],
  },

  // RURAL LIVELIHOOD SPECIALIST
  {
    qp_code: 'AHC/Q1001',
    qp_name: 'Village Level Entrepreneur (VLE)',
    sector: 'Agriculture',
    nsqf_level: 5,
    pathway_type: 'self_employment',
    gender_eligible: 'all',
    requires_mobility: false,
    requires_physical_strength: false,
    min_education_years: 10,
    typical_income_min: 12000,
    typical_income_max: 35000,
    training_duration_hours: 200,
    description: 'Provides various rural digital & financial services as a Common Service Centre operator',
    required_skills: ['computer_basics', 'communication'],
    skills_acquired: ['e-governance_services', 'financial_literacy_delivery', 'digital_payments', 'record_keeping'],
  }
];
