// =============================================================================
// Confidence Label Computation (FR-8)
// Derived from pipeline intermediate values — NOT generated by LLM.
// All inputs are logged for audit.
// =============================================================================

import type { ConfidenceLabel, ConfidenceInputs } from '@kural-sevi/shared';

export function computeConfidence(inputs: ConfidenceInputs): ConfidenceLabel {
  const {
    profile_completeness,
    stt_confidence_avg,
    extraction_certainty,
    local_data_available,
    hard_filter_passed,
    missing_fields,
  } = inputs;

  // Hard gates: if critical fields are missing or STT was very poor → needs review
  if (!hard_filter_passed) return 'needs_officer_review';
  if (missing_fields.includes('employment_preference') || missing_fields.includes('skills_and_interests')) {
    return 'needs_officer_review';
  }
  if (stt_confidence_avg < 0.5) return 'needs_officer_review';
  if (profile_completeness < 0.5) return 'needs_officer_review';

  // Compute a composite score
  let score = 0;
  score += profile_completeness * 0.35;
  score += stt_confidence_avg * 0.25;
  score += extraction_certainty * 0.20;
  score += (local_data_available ? 1 : 0) * 0.20;

  if (score >= 0.75) return 'high';
  if (score >= 0.50) return 'medium';
  return 'needs_officer_review';
}
